name = "my-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "/"

[vars]

NEXT_PUBLIC_SUPABASE_ANON_KEY =
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZGJueXhmaWFraHRsbWRiYXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODkwMjYsImV4cCI6MjA1ODI2NTAyNn0.lLikstS-MmvKy363gz_qf4qpvQcPJwjvl8iAGj6lbeY"
NEXT_PUBLIC_SUPABASE_URL = 
"https://vfdbnyxfiakhtlmdbaze.supabase.co"